### ISSUE TITLE
git-submodule-rewrite, support revisions

### ISSUE THREAD

**Issue by lsh-0** [jeremysears/scripts#15]
Hi - I've been experimenting with your git-submodule-rewrite script.

I had the assumption that, since submodules are pinned at a specific revision, when it merged the submodule into the main repository it would be done at the specific revision and not the master branch (by default).

Attempting to specify a revision in place of the branch parameter doesn't appear to work.

I'm happy to dig deeper into the script and see if I can make it work, but your choice of `master` as default instead of the pinned revision makes me suspect you encountered some problem with this approach beforehand that makes it difficult.

**Comment by jeremysears** [comment]
I can't think of any reason why you couldn't pin to a specific submodule version.  I simply didn't consider that use case.  I think you can use `git submodule status` to find the correct commit hash. 
 It seems like that behavior would be a preferable default, rather than pulling master. Feel free to submit a PR.

**Comment by lsh-0** [comment]
hey, thanks for getting back to me. I'll see what I can do with the script and open a PR. My particular usecase is that we are archiving third party repositories and some of them have submodules that should be archived at the same time to create something as close to a snapshot-in-time as possible.
